---
ID: "330cf7e5-9294-477b-b5bd-ecec161233b2"
Parent: "2123a2d7-996b-4170-a7e6-6c3b4b2bd863"
Template: "89829df8-93ee-56be-b57a-8f9efa6ba0a6"
Path: /sitecore/content/MyProject/home/Products/Product 3
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{87302B89-5BF9-4606-A3DC-51EDCB4FF620}"
              p:after="p[@uid='{C0858E4A-8D59-5AC6-9BF1-697B5BBB4D13}']"
              s:ds="{14CCFB6C-84CE-4F4C-95A0-70722214C19A}"
              s:id="{CC3195C5-D85A-46CC-BCC5-D501C48F2147}"
              s:ph="jss-main" />
            <r
              uid="{310B350D-025C-4391-BE0B-8806B009F02C}"
              p:after="r[@uid='{87302B89-5BF9-4606-A3DC-51EDCB4FF620}']"
              s:id="{A2BFDFF1-B8D3-47FE-A278-295AA5FFEFD5}"
              s:ph="jss-main" />
            <r
              uid="{ACC0160E-E80D-495B-A121-53956644B6A7}"
              p:after="*[1=2]"
              s:id="{32937322-35B7-4276-85DD-3F408D497028}"
              s:ph="NavPlaceholder" />
          </d>
        </r>
    - ID: "09265946-b966-5034-bad7-94e0d935147a"
      Hint: pageTitle
      Value: Product 3
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221218T193639Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "65d28687-e707-4a3f-89d4-035b7c634ee0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221219T151237Z
