---
ID: "c659c2ac-55b3-4922-9aaf-5d6ad63d3952"
Parent: "b47332a4-5cab-4696-8c48-6bf4378ddf66"
Template: "34844fa9-7415-4e68-bc06-fe858748f555"
Path: /sitecore/content/MyProject/home/Products/Product 2/Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04e8f048-490b-4c20-a989-c26849a5ec66"
      Hint: PDF
      Value: |
        <file mediaid="{BF0665F4-D6F3-48BB-9CD8-739EB5566051}" src="-/media/BF0665F4D6F348BB9CD8739EB5566051.ashx" />
    - ID: "07d116e1-8de7-44e9-b295-e2fd36f47009"
      Hint: Product name
      Value: Cube
    - ID: "107a1950-445c-4b85-80d9-03b7d70a6921"
      Hint: ShowInCarousel
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221218T153557Z
    - ID: "352d1113-da16-4a22-b465-02fca9526be6"
      Hint: Packaging info
      Value: 10x10x10
    - ID: "44b00e56-99e4-473c-80cf-8b46ff1cba16"
      Hint: Description
      Value: |
        Ut eu libero at ante ornare lobortis. Ut bibendum, nibh ut faucibus malesuada, ipsum leo auctor felis, sed laoreet velit purus non augue. Etiam sodales, nisi vitae convallis commodo, quam turpis pretium nibh, at accumsan ipsum ante sed ex. Praesent non porttitor metus, sed sodales enim. Vestibulum ut odio lacinia, cursus erat et, congue purus. Proin nibh felis, viverra in elit id, consequat ultrices purus. Quisque nec tempus mi, id fringilla neque.
        
        Aenean dignissim odio ac neque imperdiet dapibus. Integer ac porttitor nunc, at hendrerit ante. Pellentesque quis turpis dui. Cras tincidunt sem lorem, ut volutpat sem consectetur sed. Vivamus rhoncus cursus purus, vitae luctus est pretium nec. Fusce nisi risus, elementum non lobortis id, cursus ac nibh. Phasellus ac nisl vulputate, laoreet justo nec, porttitor arcu. In enim nulla, blandit non mollis sit amet, consectetur vel dui. Sed orci risus, interdum ac bibendum luctus, sollicitudin nec velit. Sed sodales erat quis massa venenatis iaculis id a turpis. Integer in augue sed elit faucibus sodales. Curabitur in ligula vel mauris vehicula pulvinar. Nulla facilisi. Aenean consequat dui eu condimentum pulvinar. Praesent at rutrum tellus. Nullam eu consectetur urna.
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "61436554-630c-48a9-b4ea-876b9271ea4a"
      Hint: Image
      Value: |
        <image mediaid="{D2E930D6-715E-49FC-9F5B-029065377612}" />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a5acc803-4b23-4aaf-b72a-1f5e9592e497"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221218T194749Z
