---
ID: "2123a2d7-996b-4170-a7e6-6c3b4b2bd863"
Parent: "ca3d5cc0-f313-5d94-bcf3-eccb6ade5067"
Template: "89829df8-93ee-56be-b57a-8f9efa6ba0a6"
Path: /sitecore/content/MyProject/home/Products
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{A07215BC-8256-4CF1-8A52-86712FC3EDBF}"
              p:after="p[@uid='{C0858E4A-8D59-5AC6-9BF1-697B5BBB4D13}']"
              s:id="{32937322-35B7-4276-85DD-3F408D497028}"
              s:ph="NavPlaceholder" />
            <r
              uid="{9AD13A8D-3186-4311-8D81-BA66166A419F}"
              p:after="r[@uid='{A07215BC-8256-4CF1-8A52-86712FC3EDBF}']"
              s:ds="{0D7A05AC-6886-4F9E-B0AC-1F0E02996BF1}"
              s:id="{D386A406-73C5-435F-A773-4F24FBD92491}"
              s:ph="jss-main" />
            <r
              uid="{0631FCF8-E212-44FF-A10A-0269D87BD835}"
              p:after="*[1=2]"
              s:id="{AC52C0AF-71F0-4313-A4BE-23D6CFBDB087}"
              s:ph="jss-main" />
          </d>
        </r>
    - ID: "09265946-b966-5034-bad7-94e0d935147a"
      Hint: pageTitle
      Value: Products
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221216T101248Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee5217f3-c540-4164-8c68-08c1c491de65"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221218T184256Z
